"""initial schema

Revision ID: 33127d4b27e8
Revises: 
Create Date: 2026-07-31 15:20:53.908054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33127d4b27e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_asset',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_kr', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default='KRW', nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dim_date',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('is_month_end', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('fact_financial_quarterly',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=False),
    sa.Column('fiscal_quarter', sa.SmallInteger(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('operating_income', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('eps', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bps', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['dim_asset.asset_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'fiscal_year', 'fiscal_quarter', name='uq_financial_quarter')
    )
    op.create_table('fact_market_daily',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['dim_asset.asset_id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'trade_date'),
    postgresql_partition_by='RANGE (trade_date)'
    )
    op.create_table('fact_real_estate_deal',
    sa.Column('deal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('deal_date', sa.Date(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('cap_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('mortgage_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('price_krw', sa.BigInteger(), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deal_type', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['dim_asset.asset_id'], ),
    sa.PrimaryKeyConstraint('deal_id', 'deal_date'),
    postgresql_partition_by='RANGE (deal_date)'
    )
    # ### end Alembic commands ###

    # 파티션 자식 테이블 생성 — autogenerate는 파티션 부모까지만 만들어주므로 수동으로 추가한다.
    # 연 단위 파티션 + 범위를 벗어나는 값을 받는 DEFAULT 파티션.
    for year in (2024, 2025, 2026, 2027):
        op.execute(
            f"""
            CREATE TABLE fact_market_daily_{year}
            PARTITION OF fact_market_daily
            FOR VALUES FROM ('{year}-01-01') TO ('{year + 1}-01-01')
            """
        )
        op.execute(
            f"""
            CREATE TABLE fact_real_estate_deal_{year}
            PARTITION OF fact_real_estate_deal
            FOR VALUES FROM ('{year}-01-01') TO ('{year + 1}-01-01')
            """
        )
    op.execute("CREATE TABLE fact_market_daily_default PARTITION OF fact_market_daily DEFAULT")
    op.execute("CREATE TABLE fact_real_estate_deal_default PARTITION OF fact_real_estate_deal DEFAULT")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_real_estate_deal')
    op.drop_table('fact_market_daily')
    op.drop_table('fact_financial_quarterly')
    op.drop_table('dim_date')
    op.drop_table('dim_asset')
    # ### end Alembic commands ###
